model:
  base_learning_rate: 1e-4
  target: pit.models.postprocessor.PostProcessingEngine
  params:
    input_key: img
    loss_config:
      target: TODO
      params:
        TODO: TODO
    
        regularization_weights: null

        additional_log_keys: null

    regularizer_config:
      target: pit.quantization.gaussian.GaussianQuantRegularizer
      params:
        format: bchw
        group: 16
        n_samples: 65536
        seed: 42
        beta: 2.0
        backend: torch

    encoder_config:
      target: pit.modules.unet.Encoder
      params:
        attn_type: vanilla
        double_z: true
        z_channels: 16
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        attn_resolutions: [32]
        dropout: 0.
    
    decoder_config:
      target: pit.modules.unet.Decoder
      params: ${model.params.encoder_config.params}

    post_config:
      target: pit.modules.hdit.create_hdit_model
      params:
        in_channels: 3
        out_channels: 3
        widths: [256, 512, 1024]
        depths: [2, 2, 8]
        patch_size: [4, 4]
        self_attns:
          - type: neighborhood
            d_head: 64
            kernel_size: 7
          - type: neighborhood
            d_head: 64
            kernel_size: 7
          - type: global
            d_head: 64
        mapping_depth: 2
        mapping_width: 768
        dropout_rate: [0, 0, 0]
        mapping_dropout_rate': 0.0

lightning:

  modelcheckpoint:
    params:
      every_n_train_steps: 5000
      save_top_k: -1

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 10000
  
    image_logger:
      target: main.ImageLogger
      params:
        disabled: False
        enable_autocast: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
        log_first_step: True
        log_images_kwargs:
          N: 8
          n_rows: 2
  
  trainer:
    devices: 0,1,2,3,4,5,6,7
    num_nodes: 1
    precision: 32
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    max_epochs: 10000

data:
  target: pit.data.ImageDataModuleFromConfig
  params:
    num_workers: 16
    batch_size: 16

    train:
      target: pit.data.SimpleDataset
      params:
        root: /workspace/cogview_dev/xutd/xu/datasets/ILSVRC/Data/CLS-LOC/train
        image_size: 256
